services:
  postgres:
    image: postgres:latest
    container_name: netflix_database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflix
    volumes:
      - netflix_data:/var/lib/postgresql
    networks:
      - netflix_net

  postgres_ui:
    image: sosedoff/pgweb:latest
    container_name: netflix_database_ui
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/netflix?sslmode=disable
    ports:
      - "8081:8081"
    links:
      - postgres:postgres
    depends_on:
      - postgres
    networks:
      - netflix_net

  node:
    image: node:latest
    container_name: netflix_rest_api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000

      CORS_ORIGIN: http://localhost:5173

      POSTGRES_DB: netflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      MOVIEDB_API_KEY: ${MOVIEDB_API_KEY}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 86400000

      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - netflix_net
    ports:
      - "3000:3000"
    command:
      sh -c "npm install && npm run tsc && npm run migrator:up && npm run dev"

volumes:
  netflix_data:

networks:
  netflix_net:
