services:
  postgres:
    image: postgres:latest
    container_name: netflix_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netflix
    volumes:
      - backend_data:/var/lib/postgresql
    networks:
      - backend_net

  node:
    image: node:latest
    container_name: netflix_rest
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      PORT: 3000

      CORS_ORIGIN: http://localhost:5173

      POSTGRES_DB: netflix
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432

      MOVIEDB_API_KEY: ${MOVIEDB_API_KEY}

      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 86400000

      ADMIN_USERNAME: admin
      ADMIN_EMAIL: admin@localhost
      ADMIN_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - backend_net
    ports:
      - "3000:3000"
    command:
      sh -c "npm install && npm run tsc && npm run migrator:up && npm run dev"

volumes:
  backend_data:

networks:
  backend_net:
